name: Actions

on:
  push:
    branches:
      - dev-phaser

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name:  'dev'

    steps:
      # Deploy to Azure Static Web Apps
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_DEPLOY }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          # Path to your build output folder, adjust according to your setup
          app_location: "/"
          #api_location: "api"  # Optional: If you have an API in your project, adjust as needed
          output_location: "./dist"  # Adjust this to the location of your built files (e.g., `./dist`, `./build`, etc.)
