name: Actions

on:
  push:
    branches:
      - dev-phaser

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Node.js (assuming you're using Node.js for Phaser project)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Adjust the Node.js version as necessary

      # Install dependencies (if you use npm or yarn)
      - name: Install dependencies
        run: |
          npm install # or `yarn install` if you're using Yarn

      # Build project (e.g., if using webpack or another build tool)
      - name: Build project
        run: |
          npm run build  # Replace with your build script if different

      # Deploy to Azure Static Web Apps
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_DEPLOY }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          # Path to your build output folder, adjust according to your setup
          app_location: "/"
          #api_location: "api"  # Optional: If you have an API in your project, adjust as needed
          output_location: "./dist"  # Adjust this to the location of your built files (e.g., `./dist`, `./build`, etc.)
